save_dir: './'

boards:
  - 'board_fd'
  - 'board_ca'
  - 'board_fe'
  - 'board_2e'
  - 'board_b6c5'

board_fd: 
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/1912b3e4-0ae9-11ec-b551-00056b0100fd/Train_Segments_Detrend_8K/'
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/1912b3e4-0ae9-11ec-b551-00056b0100fd/Test_Segments_Detrend_8K/'
board_ca:
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/15184b50-0ae9-11ec-896c-00056b00f8ca/Train_Segments_Detrend_8K/'
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/15184b50-0ae9-11ec-896c-00056b00f8ca/Test_Segments_Detrend_8K/'
board_fe:
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/03bcc8ae-0ae9-11ec-a87e-00183e0248fe/Train_Segments_Detrend_8K/'
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/03bcc8ae-0ae9-11ec-a87e-00183e0248fe/Test_Segments_Detrend_8K/'
board_2e:
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/269427fa-0ae9-11ec-8607-00183e02912e/Train_Segments_Detrend_8K/'
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/269427fa-0ae9-11ec-8607-00183e02912e/Test_Segments_Detrend_8K/'
board_b6c5:
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/103e5f2a-0ae9-11ec-ae28-00056b00b6c5/Train_Segments_Detrend_8K/'
  - './segments/fft/neg_edge_max_phi_max_theta_bg_sub/103e5f2a-0ae9-11ec-ae28-00056b00b6c5/Test_Segments_Detrend_8K/'

num_training: 4

all_combo_training: True


log_file: './logs/neg-backsub-maxphi-maxtheta-13class-big-text.log'

model_name: 'dense-neg-backsub-maxphi-maxtheta-13class-big-text'

dataset: 'new-variance-tuning' 

fft_freq_bins: 4095 # half of the FFT segment length - 1

epochs: 50
batch_size: 32
learning_rate: 0.00003

pca: false
pca_variance: 0.95

quantization: false
logit_total_bits: 2
logit_int_bits: 3
activation_total_bits: 2
activation_int_bits: 3

convert:
  OutputDir: dense-hls
  XilinxPart: xc7z020clg200-1
  Backend: Vivado
  IOType: io_stream
  Precision: ap_fixed<16,5>
  ClockPeriod: 10
  ReuseFactor: 200
  Strategy: Resource
