save_dir: './'

boards:
  - 'board_fd'
  - 'board_ca'
  - 'board_fe'
  - 'board_2e'
  - 'board_b6c5'

board_fd: 
  - './segments/fft/74ef25f4-094e-11ec-bcb9-00056b0100fd/Train_Segments_Neg_Detrend_8K/'
  - './segments/fft/74ef25f4-094e-11ec-bcb9-00056b0100fd/Test_Segments_Neg_Detrend_8K/'
board_ca:
  - './segments/fft/6f1e8076-094d-11ec-a2d2-00056b00f8ca/Train_Segments_Neg_Detrend_8K/'
  - './segments/fft/6f1e8076-094d-11ec-a2d2-00056b00f8ca/Test_Segments_Neg_Detrend_8K/'
board_fe:
  - './segments/fft/90e5659c-0904-11ec-a4ba-00183e0248fe/Train_Segments_Neg_Detrend_8K/'
  - './segments/fft/90e5659c-0904-11ec-a4ba-00183e0248fe/Test_Segments_Neg_Detrend_8K/'
board_2e:
  - './segments/fft/ad63c212-0973-11ec-ab31-00183e02912e/Train_Segments_Neg_Detrend_8K/'
  - './segments/fft/ad63c212-0973-11ec-ab31-00183e02912e/Test_Segments_Neg_Detrend_8K/'
board_b6c5:
  - './segments/fft/60578572-0904-11ec-b64d-00056b00b6c5/Train_Segments_Neg_Detrend_8K/'
  - './segments/fft/60578572-0904-11ec-b64d-00056b00b6c5/Test_Segments_Neg_Detrend_8K/'

num_training: 4

log_file: './logs/neg-maxphi-maxtheta-13class2.log'

model_name: 'dense-neg-maxphi-maxtheta-13class2'

dataset: 'new-variance-tuning' # FPGA'22

fft_freq_bins: 4095 # half of the FFT segment length - 1

epochs: 50
batch_size: 32
learning_rate: 0.00003

pca: false
pca_variance: 0.95

quantization: false
logit_total_bits: 2
logit_int_bits: 3
activation_total_bits: 2
activation_int_bits: 3

convert:
  OutputDir: dense-hls
  XilinxPart: xc7z020clg200-1
  Backend: Vivado
  IOType: io_stream
  Precision: ap_fixed<16,5>
  ClockPeriod: 10
  ReuseFactor: 200
  Strategy: Resource
