save_dir: './'

boards: 
  - 'board_b6c5'
  - 'board_06c5'
  - 'board_ca'
  - 'board_2e'
  - 'board_fe'

board_b6c5:
  - './segments/fft/f40b168e-f893-11eb-b613-00056b00b6c5/Train_Segments_PosNeg_Detrend_8K/'
  - './segments/fft/f40b168e-f893-11eb-b613-00056b00b6c5/Test_Segments_PosNeg_Detrend_8K/'
board_06c5:
  - './segments/fft/faa3e5f2-f893-11eb-8670-00056b0106c5/Train_Segments_PosNeg_Detrend_8K/'
  - './segments/fft/faa3e5f2-f893-11eb-8670-00056b0106c5/Test_Segments_PosNeg_Detrend_8K/'
board_ca:
  - './segments/fft/9115bf22-f71f-11eb-8e4e-00056b00f8ca/Train_Segments_PosNeg_Detrend_8K/'
  - './segments/fft/9115bf22-f71f-11eb-8e4e-00056b00f8ca/Test_Segments_PosNeg_Detrend_8K/'
board_2e:
  - './segments/fft/4749891e-f71a-11eb-a340-00183e02912e/Train_Segments_PosNeg_Detrend_8K/'
  - './segments/fft/4749891e-f71a-11eb-a340-00183e02912e/Test_Segments_PosNeg_Detrend_8K/'
board_fe:
  - './segments/fft/c5d549ae-f71e-11eb-96bd-00183e0248fe/Train_Segments_PosNeg_Detrend_8K/'
  - './segments/fft/c5d549ae-f71e-11eb-96bd-00183e0248fe/Test_Segments_PosNeg_Detrend_8K/'

num_training: 4

log_file: 'train4-test5th-NEW-pos-minphi-mentheta.txt'

model_name: 'dense-min-posneg-only-combos'

dataset: 'variance-tuning'

fft_freq_bins: 4095 # half of the FFT segment length - 1

epochs: 50
batch_size: 32
learning_rate: 0.00003

pca: false
pca_variance: 0.95

quantization: false
logit_total_bits: 2
logit_int_bits: 3
activation_total_bits: 2
activation_int_bits: 3

convert:
  OutputDir: dense-hls
  XilinxPart: xc7z020clg200-1
  Backend: Vivado
  IOType: io_stream
  Precision: ap_fixed<16,5>
  ClockPeriod: 10
  ReuseFactor: 200
  Strategy: Resource
